### ISSUE TITLE
Documentation: describe flask-ratelimiter

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/flask-ratelimiter#15]
Hi!

Reading: http://flask-ratelimiter.readthedocs.org/en/latest/ I see it is missing the very important piece of information describing what exactly the decorator does. I.e. what is the effect of this code?

```python
>>> from flask_ratelimiter import ratelimit
>>>
>>> @ratelimit(300, 200)
>>> def some_view():
>>>     return 'HelloWorld'
```

what are `300` and `200`? HTTP error codes?

The change log mentions `RATELIMITER_BACKEND_OPTIONS`. Where this and other config variables are described?

**Comment by jirikuncar** [comment]
*Flask-Ratelimiter* is deprecated in favor of *Flask-Limiter* (https://github.com/alisaifee/flask-limiter).
