### ISSUE TITLE
Responsible disclosure

### ISSUE THREAD

**Issue by twolfson** [inveniosoftware/flask-ratelimiter#19]
Hi, while researching this module for usage, I noticed a near impossible edge case but it is a security vulnerability. What is the policy on responsible disclosure? Should I file an issue or send someone an email with the details?

**Comment by jirikuncar** [comment]
Hello @twolfson, you can send us a private email to `info@invenio-software.org`. Thank you!

**Comment by twolfson** [comment]
Cool, thanks. I will send over an email outlining the issue and a proposed fix.
