### ISSUE TITLE
Allow passing in initialized Redis client and initialized backend

### ISSUE THREAD

**Issue by twolfson** [inveniosoftware/flask-ratelimiter#22]
We are interested in defining our Redis information only once in our configuration and reusing our existing initialized redis instance. This shouldn't be a problem for performance as under the hood, `redis-py` has a connection pool so no request will block another one.

```python
RateLimiterRedisBackend = RateLimiter.get_backend(app.config['RATELIMITER_BACKEND'])
rate_limiter_backend = RateLimiterRedisBackend(cache=redis_client)
RateLimiter(app=app, backend=rate_limiter_backend)
```

Here is the proposed set of changes:

https://github.com/underdogio/flask-ratelimiter/compare/dev/allow.passing.cache.base...underdogio:dev/allow.passing.cache

If you are open to accepting this in the main repo, I will add some tests and open a PR.

**Comment by jirikuncar** [comment]
> https://github.com/underdogio/flask-ratelimiter/compare/dev/allow.passing.cache.base...underdogio:dev/allow.passing.cache

@twolfson the changes look good. Please create a PR. Thanks

**Comment by twolfson** [comment]
One PR coming up :+1:

**Comment by tiborsimko** [comment]
Closing as per #24.
